using System;
namespace Behaviour.Lexemes
{
	public enum Face
	{
		OBLIQUE_BROWS, RAISE_BROWS, 
 		RAISE_LEFT_BROW, RAISE_RIGHT_BROW, 
		LOWER_BROWS, LOWER_LEFT_BROW, 
		LOWER_RIGHT_BROW, LOWER_MOUTH_CORNERS,
		LOWER_LEFT_MOUTH_CORNER, 
		LOWER_RIGHT_MOUTH_CORNER, 
		RAISE_MOUTH_CORNERS,
		RAISE_RIGHT_MOUTH_CORNER, 
		RAISE_LEFT_MOUTH_CORNER, OPEN_MOUTH, 
		OPEN_LIPS, WIDEN_EYES, CLOSE_EYES,
	}
}

