/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andri' at '2/26/16 12:40 PM' with Gradle 2.11
 *
 * @author andri, @date 2/26/16 12:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
